### ISSUE TITLE
colors of the folder names are not shown correctly in dark mode

### ISSUE THREAD

**Issue by KrisbyZottle** [ubports/settings-components#15]
e.g. when you choose a file out of the file system in suru black, the letters are not readable. The highlighted one is the one I accidentally pressed.

![screenshot20200705_183242940](https://user-images.githubusercontent.com/62804855/86539045-04cf0900-befa-11ea-8244-e75d5b79320f.png)

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/settings-components/pull/16

**Comment by jonnius** [comment]
File manager displays sure dark correctly here (RC Xperia X), even though I don't know which menu is shown exactly in the screenshot.

**Comment by jezek** [comment]
Device: FP2
OS: 2020-W49

Not fixed.

I've found out where the picture in main post is from.
In ```Settings -> VPN -> Add new manualy...``` tap on ```CA certificates``` and select ```Choose certificate...```.
With the ```suru black``` mode the menu is exactly as in the picture in main post (the bg is white, the foldere/file text is white and unreadable and the upper breadcrumbs are blue and unreadable on the black bg.

**Comment by josevidalrt** [comment]
Device: BQ E4.5
Channel: rc
Build: 2020-w49

In bq e4.5 you can reproduce the error in the colors as indicated by jezek

**Comment by laborim** [comment]
Device: Oneplus 3
Channel: rc
Build: 2020-W50

I can reproduce the error in the colors as indicated by @jezek

**Comment by jonnius** [comment]
I can confirm the issue still persists within the VPN menu using Suru Dark.

**Comment by UniversalSuperBox** [comment]
Indeed, settings-components failed to release into `xenial`. I'll fix that for OTA-16 and this will be re-QA'd then.

**Comment by cibersheep** [comment]
List items looks text white on dark background (E5)

**Comment by lgtrombetta** [comment]
Works correctly on the Nexus 6P - RC 2021-W08

**Comment by dadandalive** [comment]
Works correctly in Nexus 5 (RC 2021 - W10), also for the exact same menu as the one shown in the screenshot.
